import { MENU } from './menu.js';
const $ = s => document.querySelector(s); const money = n => `${n} GC`;
let cart = JSON.parse(localStorage.getItem('orbital-cart') || '{}');
let ratings = JSON.parse(localStorage.getItem('orbital-ratings') || '{}');
const save = () => localStorage.setItem('orbital-cart', JSON.stringify(cart));
function rating(id){return ratings[id] || 5}
function renderMenu(){ $('#menu-grid').innerHTML = ['Starters','Mains','Desserts','Drinks'].map(cat => `<div class="menu-category"><h3>${cat}<span>✦</span></h3><div class="dish-list">${MENU.filter(x=>x.category===cat).map(d=>`<article class="dish"><div class="dish-art">${d.emoji}</div><div class="dish-info"><div class="dish-title"><h4>${d.name}</h4><strong>${money(d.price)}</strong></div><p>${d.description}</p><div class="dish-bottom"><div class="stars" data-id="${d.id}">${[1,2,3,4,5].map(n=>`<button aria-label="Rate ${n}" class="star ${n<=rating(d.id)?'active':''}" data-value="${n}">★</button>`).join('')}</div><button class="add" data-add="${d.id}">+ Add</button></div></div></article>`).join('')}</div></div>`).join('');
 document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{let before=MENU.filter(d=>cart[d.id]).reduce((a,d)=>a+d.price*cart[d.id],0);cart[b.dataset.add]=(cart[b.dataset.add]||0)+1;save();renderCart();let after=MENU.filter(d=>cart[d.id]).reduce((a,d)=>a+d.price*cart[d.id],0);toast(before<=50&&after>50?'Free dessert unlocked — choose yours below!':'Added to your flight plan')});
 document.querySelectorAll('.stars').forEach(box=>box.onclick=e=>{if(!e.target.dataset.value)return; ratings[box.dataset.id]=+e.target.dataset.value;localStorage.setItem('orbital-ratings',JSON.stringify(ratings));renderMenu();updateAverage();toast('Rating received from orbit')}); }
function renderCart(){let entries=MENU.filter(d=>cart[d.id]);let sub=entries.reduce((a,d)=>a+d.price*cart[d.id],0);let discount=sub>80?sub*.1:0;let desserts=MENU.filter(d=>d.category==='Desserts');$('#cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0);$('#cart-items').innerHTML=entries.length?entries.map(d=>`<div class="cart-item"><span>${d.emoji} ${d.name}<small>${money(d.price)} each</small></span><div><button data-minus="${d.id}">−</button><b>${cart[d.id]}</b><button data-plus="${d.id}">+</button></div></div>`).join(''):'<p class="muted">Your tray is empty. The stars await.</p>';$('#subtotal').textContent=money(sub);$('#discount').textContent=`−${money(discount)}`;$('#total').textContent=money(sub-discount);$('#dessert-note').innerHTML=sub>50?`✦ Complimentary dessert unlocked — choose one:<select id="free-dessert">${desserts.map(d=>`<option value="${d.name}">${d.emoji} ${d.name}</option>`).join('')}</select>`:'';document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(b.dataset.minus,-1));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>change(b.dataset.plus,1));}
function change(id,n){cart[id]+=n;if(cart[id]<=0)delete cart[id];save();renderCart()};function updateAverage(){let vals=Object.values(ratings);let avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:4.8;$('#home-rating').textContent=avg.toFixed(1)}
function renderBookings(){let b=JSON.parse(localStorage.getItem('orbital-bookings')||'[]');$('#bookings-list').innerHTML=b.length?b.map(x=>`<div class="booking"><span>✦ <strong>${x.name}</strong></span><span>${new Date(x.date).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})} · ${x.size}</span></div>`).join(''):'<p class="muted">No tables booked yet.</p>'}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
$('#cart-drawer').classList.remove('open');$('.cart-link').onclick=e=>{e.preventDefault();$('#cart-drawer').classList.add('open')};$('#close-cart').onclick=()=>$('#cart-drawer').classList.remove('open');$('#checkout').onclick=()=>{if(Object.keys(cart).length){toast('Order transmitted — bon voyage!');cart={};save();renderCart()}else toast('Add a dish before transmitting')};$('#booking-form').onsubmit=e=>{e.preventDefault();let b=JSON.parse(localStorage.getItem('orbital-bookings')||'[]');let f=new FormData(e.target);b.push({name:f.get('name'),date:f.get('date'),size:f.get('size')});localStorage.setItem('orbital-bookings',JSON.stringify(b));e.target.reset();$('#booking-message').textContent='Coordinates locked. See you among the stars.';renderBookings()};
$('#checkout').onclick=()=>{if(Object.keys(cart).length){let dessert=$('#free-dessert')?.value;toast(dessert?`Order transmitted with complimentary ${dessert}!`:'Order transmitted — bon voyage!');cart={};save();renderCart()}else toast('Add a dish before transmitting')};
renderMenu();renderCart();renderBookings();updateAverage();
document.querySelectorAll('.pizza-add').forEach(b=>b.onclick=()=>{let d=MENU.find(x=>x.id===b.dataset.pizza), size=+$('#pizza-size').value, crust=$('#pizza-crust').value, toppings=[...document.querySelectorAll('.toppings input:checked')].map(x=>x.value), price=d.price+size+(crust.includes('+3')?3:0)+toppings.length*2;let id=`${d.id}-${Date.now()}`;MENU.push({id,name:`${d.name} · ${$('#pizza-size').selectedOptions[0].text.split(' · ')[0]}`,description:`${crust}; ${toppings.length?toppings.join(', '):'house toppings'}`,price,category:'Pizzas',emoji:'🍕'});cart[id]=1;save();renderCart();toast('Pizza built and added to your flight plan')});
