import { MENU } from './menu.js';
const $ = s => document.querySelector(s); const money = n => `${n} GC`;
let cart = JSON.parse(localStorage.getItem('orbital-cart') || '{}');
let freeDessert = localStorage.getItem('orbital-free-dessert') || '';
let ratings = JSON.parse(localStorage.getItem('orbital-ratings') || '{}');
let overallRatings = JSON.parse(localStorage.getItem('orbital-overall-ratings') || '[]');
let guestReviews = JSON.parse(localStorage.getItem('orbital-guest-reviews') || '[]');
const save = () => localStorage.setItem('orbital-cart', JSON.stringify(cart));
function rating(id){return ratings[id] || 5}
function renderMenu(){ $('#menu-grid').innerHTML = ['Starters','Mains','Desserts','Drinks'].map(cat => `<div class="menu-category"><h3>${cat}<span>✦</span></h3><div class="dish-list">${MENU.filter(x=>x.category===cat).map(d=>`<article class="dish"><div class="dish-art">${d.emoji}</div><div class="dish-info"><div class="dish-title"><h4>${d.name}</h4><strong>${money(d.price)}</strong></div><p>${d.description}</p><div class="dish-bottom"><div class="stars" data-id="${d.id}">${[1,2,3,4,5].map(n=>`<button aria-label="Rate ${n}" class="star ${n<=rating(d.id)?'active':''}" data-value="${n}">★</button>`).join('')}</div><button class="add" data-add="${d.id}">+ Add</button></div></div></article>`).join('')}</div></div>`).join('');
 document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{let before=MENU.filter(d=>cart[d.id]).reduce((a,d)=>a+d.price*cart[d.id],0);cart[b.dataset.add]=(cart[b.dataset.add]||0)+1;save();renderCart();let after=MENU.filter(d=>cart[d.id]).reduce((a,d)=>a+d.price*cart[d.id],0);toast(before<=50&&after>50?'Free dessert unlocked — choose yours below!':'Added to your flight plan')});
 document.querySelectorAll('.stars').forEach(box=>box.onclick=e=>{if(!e.target.dataset.value)return; ratings[box.dataset.id]=+e.target.dataset.value;localStorage.setItem('orbital-ratings',JSON.stringify(ratings));renderMenu();updateAverage();toast('Rating received from orbit')}); }
function renderCart(){let entries=MENU.filter(d=>cart[d.id]);let sub=entries.reduce((a,d)=>a+d.price*cart[d.id],0);let desserts=MENU.filter(d=>d.category==='Desserts');$('#cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0);$('#cart-items').innerHTML=entries.length?entries.map(d=>`<div class="cart-item"><span>${d.emoji} ${d.name}<small>${money(d.price)} each</small></span><div><button aria-label="Remove one ${d.name}" data-minus="${d.id}">−</button><b>${cart[d.id]}</b><button aria-label="Add one ${d.name}" data-plus="${d.id}">+</button></div></div>`).join(''):'<p class="muted">Your tray is empty. The stars await.</p>';$('#subtotal').textContent=money(sub);$('#discount').textContent='−0 GC';$('#total').textContent=money(sub);$('#dessert-note').innerHTML=sub>50?`✦ Complimentary dessert unlocked — choose one:<select id="free-dessert">${desserts.map(d=>`<option value="${d.id}" ${freeDessert===d.id?'selected':''}>${d.emoji} ${d.name}</option>`).join('')}</select>`:'Buy 50 GC to unlock a free dessert.';if($('#free-dessert'))$('#free-dessert').onchange=e=>{freeDessert=e.target.value;localStorage.setItem('orbital-free-dessert',freeDessert)};document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(b.dataset.minus,-1));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>change(b.dataset.plus,1));}
function change(id,n){cart[id]+=n;if(cart[id]<=0)delete cart[id];save();if(Object.keys(cart).length===0)freeDessert='';renderCart()};function updateAverage(){let vals=overallRatings;let avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:4.8;$('#home-rating').textContent=avg.toFixed(1);if($('#rating-count'))$('#rating-count').textContent=vals.length?`Based on ${vals.length} rating${vals.length===1?'':'s'}`:'Based on first contact'}
function renderBookings(){let b=JSON.parse(localStorage.getItem('orbital-bookings')||'[]');$('#bookings-list').innerHTML=b.length?b.map(x=>`<div class="booking"><span>✦ <strong>${x.name}</strong></span><span>${x.date} · ${x.time||''} · ${x.size}</span></div>`).join(''):'<p class="muted">No tables booked yet.</p>';renderBookingSlots()}
function renderBookingSlots(){let date=$('#booking-date')?.value, slots=['06:00 PM','06:30 PM','07:00 PM','07:30 PM','08:00 PM','08:30 PM','09:00 PM'], bookings=JSON.parse(localStorage.getItem('orbital-bookings')||'[]');if(!$('#booking-slots'))return;$('#booking-slots').innerHTML=date?`<p class="slot-date">Tokens for ${date}</p>${slots.map(time=>{let taken=bookings.some(x=>x.date===date&&x.time===time);return `<button type="button" class="slot-token ${taken?'occupied':''}" ${taken?'disabled':''} data-slot="${time}">${time}<small>${taken?'OCCUPIED':'AVAILABLE'}</small></button>`}).join(''):'<p class="muted">Select a date to scan available tokens.</p>';document.querySelectorAll('[data-slot]').forEach(button=>button.onclick=()=>{$('#booking-time').value=button.dataset.slot;document.querySelectorAll('[data-slot]').forEach(x=>x.classList.remove('selected'));button.classList.add('selected')})}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
$('#cart-drawer').classList.remove('open');$('.cart-link').onclick=e=>{e.preventDefault();$('#cart-drawer').classList.add('open')};$('#close-cart').onclick=()=>$('#cart-drawer').classList.remove('open');$('#checkout').onclick=()=>{if(Object.keys(cart).length){toast('Order transmitted — bon voyage!');cart={};save();renderCart()}else toast('Add a dish before transmitting')};$('#booking-form').onsubmit=e=>{e.preventDefault();let b=JSON.parse(localStorage.getItem('orbital-bookings')||'[]');let f=new FormData(e.target);b.push({name:f.get('name'),date:f.get('date'),size:f.get('size')});localStorage.setItem('orbital-bookings',JSON.stringify(b));e.target.reset();$('#booking-message').textContent='Coordinates locked. See you among the stars.';renderBookings()};
$('#checkout').onclick=()=>{if(Object.keys(cart).length){let dessert=MENU.find(d=>d.id===($('#free-dessert')?.value||freeDessert));toast(dessert?`Order transmitted with complimentary ${dessert.name}!`:'Order transmitted — bon voyage!');cart={};freeDessert='';localStorage.removeItem('orbital-free-dessert');save();renderCart()}else toast('Add a dish before transmitting')};
renderMenu();renderCart();renderBookings();updateAverage();
let selectedRating=0;document.querySelectorAll('[data-overall]').forEach(button=>button.onclick=()=>{selectedRating=+button.dataset.overall;document.querySelectorAll('[data-overall]').forEach(x=>x.classList.toggle('selected',+x.dataset.overall<=selectedRating))});$('#rating-form').onsubmit=e=>{e.preventDefault();let text=$('#review-text').value.trim();if(!selectedRating||!text){$('#rating-feedback').textContent='Choose a star rating and write a review first.';return}overallRatings.push(selectedRating);guestReviews.unshift({rating:selectedRating,text});localStorage.setItem('orbital-overall-ratings',JSON.stringify(overallRatings));localStorage.setItem('orbital-guest-reviews',JSON.stringify(guestReviews));updateAverage();$('#review-grid').insertAdjacentHTML('afterbegin',`<article><div class="rating-stars">${'★'.repeat(selectedRating)}${'☆'.repeat(5-selectedRating)}</div><p>“${text.replace(/[<>]/g,'')}”</p><small>— Recent explorer</small></article>`);e.target.reset();selectedRating=0;document.querySelectorAll('[data-overall]').forEach(x=>x.classList.remove('selected'));$('#rating-feedback').textContent='Transmission received — thank you, explorer.';toast('Review recorded')};
$('#booking-date').onchange=renderBookingSlots;renderBookingSlots();
document.querySelectorAll('.pizza-add').forEach(b=>b.onclick=()=>{let d=MENU.find(x=>x.id===b.dataset.pizza), size=+$('#pizza-size').value, crust=$('#pizza-crust').value, toppings=[...document.querySelectorAll('.toppings input:checked')].map(x=>x.value), price=d.price+size+(crust.includes('+3')?3:0)+toppings.length*2;let id=`${d.id}-${Date.now()}`;MENU.push({id,name:`${d.name} · ${$('#pizza-size').selectedOptions[0].text.split(' · ')[0]}`,description:`${crust}; ${toppings.length?toppings.join(', '):'house toppings'}`,price,category:'Pizzas',emoji:'🍕'});cart[id]=1;save();renderCart();toast('Pizza built and added to your flight plan')});
const originalBookingForm=$('#booking-form');originalBookingForm.onsubmit=e=>{e.preventDefault();let f=new FormData(e.target), contact=f.get('email')||f.get('phone');if(!contact){$('#booking-message').textContent='Please add an email or phone number for confirmation.';return}let bookings=JSON.parse(localStorage.getItem('orbital-bookings')||'[]');let key=`${f.get('date')} ${f.get('time')}`;if(bookings.some(x=>x.key===key)){ $('#booking-message').textContent='That landing slot is already occupied. Choose another token.';return}bookings.push({key,name:f.get('name'),date:f.get('date'),time:f.get('time'),size:f.get('size'),contact});localStorage.setItem('orbital-bookings',JSON.stringify(bookings));e.target.reset();$('#booking-message').textContent=`Coordinates locked. Confirmation sent to ${contact}.`;renderBookings()};
